### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by MorningSleeper** [qooob/authentic-theme-extensions#1]
Hi, when trying to add some extensions I get the following errors. What type of permission should those files have?

Failed to open /etc/webmin/authentic-theme/styles.css for writing : Permission denied
Failed to open /etc/webmin/authentic-theme/scripts.js for writing : Permission denied
Failed to open /etc/webmin/authentic-theme/favorites.json for writing : Permission denied

**Comment by qooob** [comment]
Interesting.. never encountered it before.. Try to make sure that the file's permissions correspond with the one that Webmin is running from. 

Execute from terminal `ls -lsa /etc/webmin/authentic-theme/` what do you get?

**Comment by MorningSleeper** [comment]
How do I find out the permissions that Webmin is running from? I get the following from the command:

ubuntu@server1:~$ ls -lsa /etc/webmin/authentic-theme/
total 16
4 drwxr-xr-x   2 root root 4096 Aug 28 12:11 .
4 drwxr-xr-x 124 root root 4096 Aug 28 12:29 ..
4 -rw-r--r--   1 root root  114 Aug 28 12:07 config
4 -rw-r--r--   1 root root 1830 Aug 28 12:11 settings.js

**Comment by qooob** [comment]
All seems fine! To find out about Webmin, run `ps aux | grep -v grep | grep webmin`

**Comment by MorningSleeper** [comment]
Ok, got the following:

ubuntu@server1:~$ ps aux | grep -v grep | grep webmin
root      2369  0.0  1.2  93216 12236 ?        Ss   Aug18   0:14 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf

**Comment by qooob** [comment]
Seem alright too. Ok.

Not sure..

Try

1. 
`touch /etc/webmin/authentic-theme/styles.css`
`touch /etc/webmin/authentic-theme/scripts.js`
`touch /etc/webmin/authentic-theme/favorites.json`

2. If doesn't work, try to open `/usr/libexec/webmin/authentic-theme/settings-editor_write.cgi` and comment out/remove the following line `&switch_to_remote_user();`. To comment it out just add `#` infront of it. After, reload Webmin. 

Does it work?

**Comment by MorningSleeper** [comment]
Tried 1, created files but still got permission error. So I tried 2, I did not have the directory you wrote but did find the file in /usr/share/webmin/authentic-theme/settings-editor_write.cgi

I commented out the line, restarted Webmin and now I don't get the permissions error and it saves the file data, thanks! BTW, i see the number 20 in the favorites.json what is that for and should it not be removed?

**Comment by qooob** [comment]
> i see the number 20 in the favorites.json what is that for and should it not 

You see it where? Can you make screenshot?

**Comment by MorningSleeper** [comment]
In the textarea field. No matter what I put in there and try to save, it reloads the page with a 20 in there and nothing else.

![capture](https://cloud.githubusercontent.com/assets/8920632/9556443/9a1ed144-4d89-11e5-9b3d-7c03884a727a.PNG)

**Comment by qooob** [comment]
Well. You should not bother about this! It should be just alright! The regex will that care about not getting junk out from JSON. Thank you for reporting! I will fix it in version 15.50 within next 15 hours.

**Comment by MorningSleeper** [comment]
Ok, thanks for the help.

**Comment by qooob** [comment]
I missed it. You say no matter what you put there and save it doesn't work? Do you put there JSON type object? When you save favorites, just reload the page, do you see nicely formatted object?

**Comment by MorningSleeper** [comment]
no, I just tested with some random text, can you provide an example JSON type object I can test with?

**Comment by qooob** [comment]
No, its not correct in this context. Just click on the star at the header, then click right Moise button and reload THIS frame..

**Comment by MorningSleeper** [comment]
I added the page as a favorite by clicking star in header and reloaded just that frame, still just shows 20 in textarea. Favorite was saved as shows up when I click the star in bottom left column.

**Comment by qooob** [comment]
If you reload everything, will you still see the favorited page. If you click on the save favorite does it take you where expected?

**Comment by MorningSleeper** [comment]
I see the favorite when I click the star in bottom left column and it takes me to where I expected fine. Just does not appear in the extension textarea, should it appear in there as well?

**Comment by qooob** [comment]
Well yes, this is how it looks on my end. Try to manually find this file on the server and take a look into it!

![screenshot from 2015-08-29 11-09-19](https://cloud.githubusercontent.com/assets/4426533/9561062/9a0593f4-4e3e-11e5-9f12-9e8282fb7cb5.png)

**Comment by MorningSleeper** [comment]
The file was empty, does not even have 20 in it. I changed the permissions from 644 to 666 and now when i save a favorite the textarea field shows content similar to your screen shot and no 20 in it. So what should the permissions be on that file.

**Comment by qooob** [comment]
They should be automatically detected and set. Try to delete the file manually. Then add/remove from the favorites currently open page (without reload). What are the file permissions now on the favorites.json file?

**Comment by MorningSleeper** [comment]
If I delete the file, it is not automatically created when i add a favorite. I have to touch it as you recommended earlier. That creates the file with 644 permissions but when I add a favorite it still can't write to it. I have to either change permissions to 666 or set it back to 644 and comment out the &switch_to_remote_user(); in /usr/share/webmin/authentic-theme/settings-favorites_save.cgi for it to save to the file.

**Comment by qooob** [comment]
So if you start from the _clear_ with commented out `switch_to_remote_user()` everything works ok, you don't need to touch it?

**Comment by MorningSleeper** [comment]
Correct

**Comment by qooob** [comment]
Ok. I will take a closer look and probably remove that line as well. Thanks, pal! ;)

**Comment by MorningSleeper** [comment]
ok, thanks for the help.
